### ISSUE TITLE
sha256 hashing of JSON documents

### ISSUE THREAD

**Issue by pimg** [dcsaorg/DCSA-EBL-Envelope#5]
The EBL Envelope transfers requires SHA-256 hashes of the EBL document (Transport document) and EBL envelopes, which are JSON documents. Calculating SHA-256 hashes directly in JSON documents can lead to inconsistencies. 

We should consider to calculate the SHA-256 hash the cannonified JSON document to prevent mismatches in character encodings and formatting discrepancies. RFC8785 seems most appropriate for this purpose: https://datatracker.ietf.org/doc/html/rfc8785

**Comment by pimg** [comment]
another solution could be to move from the detached unencoded payload to an encoded JWS

**Comment by raisoman** [comment]
The envelopes and documents should be immutable and their binary representation constant. In consequence it is not obvious to me why canonicalization is needed as such.

This issue reportedly stems from a concrete case of SHA256 hashes not matching. Can we possibly get access to the given envelopes in order to reproduce the error?

**Comment by pimg** [comment]
there was an issue where the receiving service formatted the http payload slightly differently (pretty printed) the json message. Resulting in a different hash upon verification. This could potentially be mitigated by mandating RFC8785 formatting. Or to be even more robust encode the JSON as base64
